spring:
  application:
    name: api-gateway
server:
  port: 5555
zuul:
  routes:
#    api-a:
#      path: /api-a/**
#      serviceId: eureka-client
#    api-b:
#      path: /api-b/**
#      serviceId: feign-consumer
    eureka-client: /eureka-client/** #用来替代上面path和serviceId的配置
    feign-consumer: /feign-consumer/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#zuul:
#  routes:
#    api-a-url:
#      path: /api-a-url/**           #传统路由方式,当访问localhost:5555/api-a-url/hello时,
#      url: http://localhost:8080   #API网关服务会将该请求路由到http://localhost:8080/hello提供的微服务接口上

#zuul:
#  routes:
#    api-a-url:
#      path: /api-a-url/**           #传统路由方式,多节点配置,当访问localhost:5555/api-a-url/hello时,
#      serviceId: eureka-client   #API网关服务会将该请求路由到eureka-client/hello提供的微服务接口上
#eureka-client:
#  ribbon:
#    listOfServers: http://localhost:8080/,http://localhost:8081/