server:
  port: 8191
spring:
  application:
    name: eureka-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#      defaultZone: http://peer1:8182/eureka/,http://peer2:8181/eureka/