spring:
  application:
    name: api-gateway
  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8888/
server:
  port: 5556
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  security:
    enabled: false