spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ghf704694314/configRepo
          search-paths: userConfig
          username: 704694314@qq.com
          password: 88979150aa
      label: master
server:
  port: 8888